import Head from 'next/head';
import React, { useState } from 'react';
import styled from 'styled-components';

import ViewContext from '../contexts/ViewContext';
import Nav from './Nav';

const PageWrapper = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: ${(props) => props.theme.colors.primary};
  overflow: auto;
`;

const Main = styled.main`
  flex-grow: 1;
  display: flex;
  flex-direction: column;
`;

const Layout: React.FC = function (props) {
  const { children } = props;

  const [view, setView] = useState<string>('colors');

  return (
    <ViewContext.Provider value={{ view, setView }}>
      <Head>
        <title>snob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <Nav />

        <Main>{children}</Main>

        <footer></footer>
      </PageWrapper>
    </ViewContext.Provider>
  );
};

export default Layout;
