import Head from 'next/head';
import React from 'react';
import styled from 'styled-components';

const PageWrapper = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
`;

const Layout: React.FC = function (props) {
  const { children } = props;

  return (
    <>
      <Head>
        <title>snob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageWrapper>{children}</PageWrapper>
      </main>

      <footer></footer>
    </>
  );
};

export default Layout;
