import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styled from 'styled-components';

const StyledLink = styled.a`
  display: block;
  width: 100%;
  text-align: center;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>snob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="staticGen" passHref><StyledLink>Static Generation</StyledLink></Link>
        <Link href="ssr" passHref><StyledLink>Server-side Rendering</StyledLink></Link>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
