import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>snob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Link href="staticGen"><a>Static Generation</a></Link>
        <Link href="ssr"><a>Server-side Rendering</a></Link>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
